import React, { Component } from 'react';
import UserContext from '../components/UserContext';

export default class Home extends Component {
    static contextType = UserContext;

    render() {
        console.log(this);
        return (
            <>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris bibendum tortor at lacus feugiat commodo. Aliquam nec vestibulum lacus, a semper purus. Ut in nunc sapien. Nullam suscipit sollicitudin pharetra. Sed iaculis nulla in eros interdum, eu luctus dui volutpat. Nullam vulputate eget lacus ut semper. Praesent finibus tempus dapibus. Mauris dignissim tempus venenatis. Curabitur mollis id lorem in bibendum. Pellentesque non semper risus. Praesent euismod sit amet nisi vitae suscipit.</p>
                <p>Nunc auctor finibus nunc, ut commodo magna. Curabitur maximus nunc at felis blandit, ut aliquet mauris vulputate. Aenean non porta massa. Nam at tempor ligula. Pellentesque pulvinar vestibulum tortor nec blandit. Mauris ullamcorper purus sed ante eleifend, id suscipit risus rutrum. Pellentesque ultricies rhoncus mi sit amet rutrum. Quisque eget congue felis. Mauris id nunc justo. Cras felis turpis, luctus sed metus eget, interdum vestibulum mi. Cras nec ex in mi pharetra imperdiet in quis massa. Etiam dignissim libero a eleifend vestibulum. Sed id justo facilisis mauris faucibus semper. Etiam lobortis ligula non leo cursus, et dapibus ligula porttitor.</p>
                <p>Cras convallis bibendum est, sit amet lacinia tellus luctus vel. Praesent condimentum faucibus euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse aliquet quam consequat, malesuada tortor sit amet, pulvinar justo. Duis blandit turpis sed nulla tincidunt congue. Aenean aliquet dignissim tempor. Nunc vel eleifend ex. Nulla quis egestas sapien, ac hendrerit dui. Ut mollis fermentum felis vitae faucibus. Integer mattis quis nisl sed faucibus. Phasellus dignissim accumsan est. Sed quis semper tellus. Cras lobortis quis sem lobortis porta. Nulla bibendum finibus ipsum ac pellentesque. Mauris consectetur ligula in vehicula elementum.</p>
                <p>Aliquam vitae pellentesque neque, viverra facilisis leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras in libero interdum, euismod odio nec, pretium lectus. Cras dolor purus, fringilla eget est non, tempor egestas felis. Curabitur sem sem, mattis at tincidunt luctus, pharetra ut dolor. Donec suscipit accumsan lorem, in ornare velit pharetra non. Nulla molestie mollis lacus volutpat pretium. Sed et dui metus. Ut consectetur bibendum massa, nec porta justo.</p>
                <p>Proin porttitor justo sit amet porttitor vehicula. In cursus, felis id ultrices pellentesque, nisl leo faucibus velit, vitae commodo diam neque eget risus. Sed gravida lectus urna, et gravida diam convallis non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean tincidunt pharetra sem, id elementum felis elementum a. Aenean sed ultricies est, a commodo eros. Fusce massa urna, dapibus quis facilisis sit amet, ullamcorper at odio.</p>
                <p>Maecenas malesuada ac justo sit amet dictum. Mauris ac laoreet neque. Mauris ultricies volutpat arcu vitae fringilla. Ut bibendum quam eu dolor pellentesque rutrum. Aenean finibus massa neque, non tincidunt enim porttitor a. Nullam imperdiet tincidunt velit, quis sodales turpis tempus sed. Sed in risus ac augue tempus porta et in est. Nunc malesuada vehicula ipsum eu mollis. Fusce efficitur turpis magna, non fringilla est maximus non. Praesent libero erat, luctus at consequat at, posuere non diam.</p>
                <p>Morbi placerat, metus nec sodales tempus, enim ligula ultrices erat, sit amet vestibulum lorem lorem in dolor. Etiam nisl sapien, vestibulum sit amet ipsum in, laoreet accumsan diam. Donec facilisis orci vitae arcu eleifend ullamcorper. Etiam vel mi sed lacus molestie congue id at dui. Suspendisse maximus mauris at lorem scelerisque, at sollicitudin orci cursus. Nulla quis lectus ut magna dictum lacinia. Morbi vitae nibh urna. Sed et leo a lectus venenatis tempor. Integer vehicula sem diam, et gravida velit porta in.</p>
                <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla at rhoncus sapien. Cras neque justo, tincidunt eu ligula sagittis, tincidunt condimentum lorem. Fusce porttitor tortor egestas, porttitor tellus id, interdum diam. Suspendisse sit amet odio porttitor, interdum magna vitae, tristique velit. Quisque nec ornare mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec a pellentesque elit, at semper lacus. Aliquam porta, quam vitae luctus feugiat, massa diam luctus nibh, ac efficitur est velit id felis. Proin aliquet lacus sem, sed aliquet nisl dignissim quis. In interdum ante in lorem tristique, eget hendrerit lacus aliquam. Fusce vel imperdiet dolor, quis bibendum nulla.</p>
                <p>Proin varius rutrum justo, vitae pellentesque odio lacinia ut. In eu felis egestas, accumsan eros ut, efficitur risus. Ut in lacus felis. Pellentesque sollicitudin at purus ut dapibus. Nunc luctus hendrerit tincidunt. Duis sapien metus, rutrum vitae arcu id, euismod malesuada turpis. Morbi viverra, elit eget rhoncus tincidunt, justo nisl molestie eros, a vehicula purus ipsum ac turpis. Sed facilisis eros quis urna vulputate faucibus.</p>
                <p>In a eleifend est, sit amet sollicitudin ligula. Pellentesque ac efficitur ligula, eu fringilla elit. Donec ac aliquet mi. Donec eleifend nunc ac tempus semper. Phasellus pulvinar ex in est finibus, quis rhoncus lacus vestibulum. Proin varius, arcu sit amet tempus luctus, arcu massa viverra diam, non mattis lacus arcu sed nulla. Maecenas maximus libero condimentum dolor ultricies ultrices. Vivamus convallis condimentum libero, id tempus nibh ullamcorper ut. Nunc fermentum, arcu nec accumsan tempus, erat urna fringilla erat, a feugiat lorem erat non lectus. Aenean elit lacus, facilisis ut arcu et, facilisis fringilla lectus. Suspendisse rutrum sagittis efficitur. Etiam suscipit purus id posuere tincidunt. Nam condimentum nunc quis sem consectetur tincidunt. Vivamus bibendum, urna at pharetra efficitur, odio sapien bibendum ex, ac maximus tellus lacus ac tellus. Integer interdum nisl tortor. Aliquam varius convallis molestie.</p>
            </>
        );
    }
}